apiVersion: v1
kind: Service
metadata:
  name: t1-service
spec:
  selector:
    app: t1
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t1
spec:
  selector:
    matchLabels:
      app: t1
  replicas: 1
  template:
    metadata:
      labels:
        app: t1
    spec:
      containers:
      - name: t1
        image: gowthamg404/t1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
